# Site settings
title: BootstrapDenton
email: info@techmill.co
description: > # this means to ignore newlines until "baseurl:"
  Bootstrap Denton is a series of events designed to create networking opporunities, and educate entrepreneurs, and support our growing startup community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bootstrapdenton.com" # the base hostname & protocol for your site
twitter_username: techmilldenton
github_username:  techmill
facebook_username:  techmilldenton

# Build settings
markdown: kramdown
